create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null,
  password varchar(255),
  name varchar(255) not null,
  school varchar(255),
  major varchar(255),
  grade integer,
  role varchar(255),
  verified boolean not null default false,
  avatar_url text,
  created_at timestamp,
  updated_at timestamp
);

create unique index if not exists ux_users_email on users (email);

create table if not exists opportunities (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  organization varchar(255),
  category varchar(255),
  description text,
  requirements text,
  benefits text,
  target varchar(255),
  deadline date,
  start_date date,
  end_date date,
  location varchar(255),
  is_online boolean,
  apply_url varchar(1000),
  thumbnail_url varchar(255),
  status varchar(255),
  popularity_count integer,
  recommended boolean not null default false,
  new_this_week boolean not null default false,
  created_at timestamp,
  updated_at timestamp
);

create index if not exists ix_opportunities_deadline on opportunities (deadline);
create index if not exists ix_opportunities_category_deadline on opportunities (category, deadline);
create index if not exists ix_opportunities_apply_url on opportunities (apply_url);
create index if not exists ix_opportunities_duplicate_key on opportunities (title, organization, deadline);

create table if not exists opportunity_tags (
  opportunity_id bigint not null,
  tag varchar(255)
);

create index if not exists ix_opportunity_tags_opportunity_id on opportunity_tags (opportunity_id);

create table if not exists saved_opportunities (
  id bigint generated by default as identity primary key,
  user_id bigint,
  opportunity_id bigint,
  created_at timestamp
);

create unique index if not exists ux_saved_opportunities_user_opportunity
  on saved_opportunities (user_id, opportunity_id);
create index if not exists ix_saved_opportunities_user_id on saved_opportunities (user_id);

create table if not exists application_records (
  id bigint generated by default as identity primary key,
  user_id bigint,
  opportunity_id bigint,
  status varchar(255),
  memo text,
  created_at timestamp,
  updated_at timestamp
);

create index if not exists ix_application_records_user_id on application_records (user_id);
create index if not exists ix_application_records_opportunity_id on application_records (opportunity_id);

create table if not exists community_posts (
  id bigint generated by default as identity primary key,
  user_id bigint,
  opportunity_id bigint,
  type varchar(255),
  title varchar(255),
  content text,
  created_at timestamp,
  updated_at timestamp
);

create index if not exists ix_community_posts_user_id on community_posts (user_id);
create index if not exists ix_community_posts_opportunity_id on community_posts (opportunity_id);
create index if not exists ix_community_posts_created_at on community_posts (created_at);

create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint,
  user_id bigint,
  content text,
  created_at timestamp,
  updated_at timestamp
);

create index if not exists ix_comments_post_id on comments (post_id);

create table if not exists mentor_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint,
  company varchar(255),
  position varchar(255),
  experience text,
  available boolean not null default false,
  created_at timestamp,
  updated_at timestamp
);

create index if not exists ix_mentor_profiles_user_id on mentor_profiles (user_id);

create table if not exists mentor_help_topics (
  mentor_profile_id bigint not null,
  help_topic varchar(255)
);

create index if not exists ix_mentor_help_topics_profile_id on mentor_help_topics (mentor_profile_id);

create table if not exists mentor_questions (
  id bigint generated by default as identity primary key,
  mentor_id bigint,
  user_id bigint,
  opportunity_id bigint,
  content text,
  status varchar(255),
  created_at timestamp,
  updated_at timestamp
);

create index if not exists ix_mentor_questions_mentor_id on mentor_questions (mentor_id);
create index if not exists ix_mentor_questions_user_id on mentor_questions (user_id);

create table if not exists opportunity_sources (
  id bigint generated by default as identity primary key,
  name varchar(255),
  type varchar(255),
  base_url varchar(1000),
  category_hint varchar(255),
  crawl_interval_minutes integer,
  robots_allowed boolean not null default false,
  enabled boolean not null default false,
  last_crawled_at timestamp,
  failure_count integer,
  created_at timestamp,
  updated_at timestamp
);

create unique index if not exists ux_opportunity_sources_name on opportunity_sources (name);

create table if not exists raw_opportunities (
  id bigint generated by default as identity primary key,
  source_id bigint,
  external_id varchar(255),
  source_url varchar(1000),
  raw_title varchar(255),
  raw_content text,
  raw_payload text,
  content_hash varchar(255),
  fetched_at timestamp,
  last_seen_at timestamp,
  normalized_opportunity_id bigint,
  status varchar(255),
  error_message text
);

create index if not exists ix_raw_opportunities_source_hash on raw_opportunities (source_id, content_hash);
create index if not exists ix_raw_opportunities_status on raw_opportunities (status);
create index if not exists ix_raw_opportunities_fetched_at on raw_opportunities (fetched_at);

create table if not exists crawl_jobs (
  id bigint generated by default as identity primary key,
  source_id bigint,
  status varchar(255),
  started_at timestamp,
  finished_at timestamp,
  items_found integer,
  items_created integer,
  items_updated integer,
  error_message text
);

create index if not exists ix_crawl_jobs_source_id on crawl_jobs (source_id);
create index if not exists ix_crawl_jobs_status on crawl_jobs (status);
