create table if not exists community_post_saves (
  id bigint generated by default as identity primary key,
  post_id bigint not null,
  user_id bigint not null,
  created_at timestamp not null
);

create unique index if not exists ux_community_post_saves_post_user
  on community_post_saves (post_id, user_id);
create index if not exists ix_community_post_saves_user_id
  on community_post_saves (user_id);

alter table community_post_saves add constraint fk_community_post_save_post
  foreign key (post_id) references community_posts(id) on delete cascade;
alter table community_post_saves add constraint fk_community_post_save_user
  foreign key (user_id) references users(id) on delete cascade;
