import { createContext, useContext, useEffect, useMemo, useState } from "react";

const copy = {
  en: {
    "nav.home": "Home",
    "nav.explore": "Explore",
    "nav.community": "Community",
    "nav.mentors": "Mentors",
    "nav.saved": "Saved",
    "nav.profile": "Profile",
    "nav.admin": "Admin",
    "nav.crawl": "Crawl",
    "nav.search": "Search",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.korean": "Korean",
    "settings.english": "English",
    "home.kicker": "Find opportunities that fit you.",
    "home.title": "Find the career that fits you.",
    "home.heroTitle": "Find the career that fits you.",
    "home.heroCopy": "Meet internships, competitions, and scholarships that help you grow faster.",
    "home.saved": "saved",
    "home.searchPlaceholder": "Search internships, scholarships, contests...",
    "home.featuredLabel": "Featured for you",
    "home.aiRecommendation": "AI recommendation",
    "home.categories": "Browse by category",
    "home.summaryTitle": "Today's summary",
    "home.metricsTitle": "At a glance",
    "home.featuredSection": "Top match",
    "home.matchLabel": "match",
    "home.featuredNote": "Recommendation strength is based on your profile and interests.",
    "home.homeCtaCopy": "Use the navigation above or start exploring opportunities now.",
    "home.homeCtaAction": "Explore now",
    "explore.matches": "matches",
    "explore.title": "Explore opportunities.",
    "filters.search": "Search",
    "filters.placeholder": "Title, organization, category, location, tag",
    "filters.targetPlaceholder": "Major, grade, or eligibility keyword",
    "filters.category": "Category",
    "filters.region": "Region",
    "filters.sort": "Sort",
    "filters.quick": "Quick filters",
    "filters.deadlineSoon": "Deadline soon",
    "filters.online": "Online",
    "filters.offline": "Offline",
    "filters.saved": "Saved",
    "card.save": "Save",
    "card.saved": "Saved",
    "card.viewDetails": "View Details",
    "card.saves": "saves",
    "sort.deadline": "Deadline",
    "sort.latest": "Newest",
    "sort.title": "Title",
    "sort.popular": "Most saved",
    "detail.notFoundTitle": "Opportunity not found.",
    "detail.notFoundDescription": "Return to Explore and choose another opportunity.",
    "detail.apply": "Apply Now",
    "detail.deadline": "Deadline",
    "detail.location": "Location",
    "location.Nationwide": "Nationwide",
    "detail.period": "Period",
    "detail.target": "Target",
    "detail.description": "Description",
    "detail.requirements": "Requirements",
    "detail.benefits": "Benefits",
    "detail.howToApply": "How to apply",
    "detail.applyCopy": "Prepare the required materials, confirm eligibility, and apply through the official link before the deadline.",
    "detail.sourceFallback": "Check the official source for details.",
    "detail.record": "Application Record",
    "detail.related": "Related opportunities",
    "detail.qa": "Related Q&A",
    "detail.openCommunity": "Open community",
    "detail.mentors": "Related mentors",
    "detail.viewMentors": "View mentors",
    "common.emptyTitle": "No opportunities yet.",
    "common.emptyDescription": "Try another category or clear filters.",
    "common.errorTitle": "Something went wrong.",
    "common.errorDescription": "Check your connection and try again.",
    "common.retry": "Retry",
    "common.loading": "Saving...",
    "common.loginRequiredTitle": "Login required.",
    "common.loginRequiredDescription": "Sign in to use saved opportunities and profile features.",
    "common.goLogin": "Go to login",
    "login.title": "Sign in to Campio",
    "login.copy": "Continue to your personalized opportunity feed.",
    "login.email": "Email",
    "login.password": "Password",
    "login.action": "Login",
    "login.loading": "Logging in...",
    "login.create": "Create account",
    "login.logout": "Logout",
    "signup.title": "Create your Campio account",
    "signup.copy": "Set up your profile and personalize opportunity recommendations.",
    "signup.name": "Name",
    "signup.schoolEmail": "School email",
    "signup.avatar": "Profile image",
    "signup.avatarHelp": "Choose a square image under 1 MB.",
    "signup.avatarError": "Please choose an image under 1 MB.",
    "signup.continue": "Continue",
    "signup.loading": "Creating account...",
    "signup.haveAccount": "I already have an account",
    "onboarding.title": "Personalize Campio",
    "onboarding.copy": "Add your school profile and choose the interests that shape your feed.",
    "onboarding.school": "School",
    "onboarding.major": "Major",
    "onboarding.grade": "Grade",
    "saved.kicker": "Manage opportunities you care about",
    "saved.title": "Saved opportunities.",
    "saved.emptyTitle": "No saved opportunities yet.",
    "saved.emptyDescription": "Explore opportunities and save the ones you like.",
    "saved.explore": "Explore",
    "community.kicker": "Questions, reviews, tips, and information",
    "community.title": "Community.",
    "community.popular": "Popular Questions",
    "community.writeTitle": "Title",
    "community.writeTitlePlaceholder": "Ask about an opportunity, deadline, interview, or preparation",
    "community.writeContent": "Content",
    "community.writeContentPlaceholder": "Share the context so other students can help.",
    "community.writeAction": "Post",
    "community.emptyTitle": "No community posts yet.",
    "community.emptyDescription": "Ask the first question about an opportunity or application process.",
    "mentors.kicker": "Mentors help students use opportunities better",
    "mentors.title": "Mentors.",
    "mentors.available": "Available mentors",
    "mentors.emptyTitle": "No mentors available yet.",
    "mentors.emptyDescription": "Mentor matching will become useful after verified mentor profiles are added.",
    "profile.kicker": "School profile",
    "profile.school": "School",
    "profile.major": "Major and grade",
    "profile.saved": "Saved opportunities",
    "profile.interests": "Interests",
    "admin.kicker": "Admin opportunity CRUD foundation",
    "admin.title": "Admin Opportunities.",
    "admin.create": "Create Opportunity",
    "admin.colTitle": "Title",
    "admin.colCategory": "Category",
    "admin.colOrganization": "Organization",
    "admin.colDeadline": "Deadline",
    "admin.colStatus": "Status",
    "admin.published": "published",
  },
  ko: {
    "nav.home": "홈",
    "nav.explore": "탐색",
    "nav.community": "커뮤니티",
    "nav.mentors": "멘토",
    "nav.saved": "저장",
    "nav.profile": "내 정보",
    "nav.admin": "관리",
    "nav.crawl": "수집",
    "nav.search": "검색",
    "settings.language": "언어",
    "settings.theme": "테마",
    "settings.light": "라이트",
    "settings.dark": "다크",
    "settings.korean": "한국어",
    "settings.english": "English",
    "home.kicker": "나에게 맞는 기회를 찾아보세요.",
    "home.title": "나에게 딱 맞는 커리어를 찾아보세요.",
    "home.heroTitle": "나에게 딱 맞는 커리어를 찾아보세요.",
    "home.heroCopy": "나를 한 단계 성장시킬 인턴십, 공모전, 장학금을 가장 빠르게 만나보세요.",
    "home.saved": "저장됨",
    "home.searchPlaceholder": "인턴십, 장학금, 공모전을 검색해보세요",
    "home.featuredLabel": "추천 기회",
    "home.aiRecommendation": "AI 추천",
    "home.categories": "카테고리별 탐색",
    "home.summaryTitle": "오늘의 요약",
    "home.metricsTitle": "한눈에 보기",
    "home.featuredSection": "가장 잘 맞는 기회",
    "home.matchLabel": "일치",
    "home.featuredNote": "프로필과 관심사를 기준으로 추천 적합도를 계산했어요.",
    "home.homeCtaCopy": "원하는 메뉴를 상단 탭에서 선택하거나, 지금 바로 커리어를 탐색해 보세요!",
    "home.homeCtaAction": "지금 탐색하러 가기",
    "explore.matches": "개 결과",
    "explore.title": "기회를 탐색하세요.",
    "filters.search": "검색",
    "filters.placeholder": "제목, 기관, 카테고리, 지역, 태그",
    "filters.targetPlaceholder": "전공, 학년, 지원 대상 키워드",
    "filters.category": "카테고리",
    "filters.region": "지역",
    "filters.sort": "정렬",
    "filters.quick": "빠른 필터",
    "filters.deadlineSoon": "마감 임박",
    "filters.online": "온라인",
    "filters.offline": "오프라인",
    "filters.saved": "저장됨",
    "card.save": "저장",
    "card.saved": "저장됨",
    "card.viewDetails": "자세히 보기",
    "card.saves": "명이 저장",
    "sort.deadline": "마감일순",
    "sort.latest": "최신순",
    "sort.title": "제목순",
    "sort.popular": "인기순",
    "detail.notFoundTitle": "기회를 찾을 수 없어요.",
    "detail.notFoundDescription": "탐색 화면에서 다른 기회를 선택해 주세요.",
    "detail.apply": "지원하기",
    "detail.deadline": "마감일",
    "detail.location": "위치",
    "location.Nationwide": "전국",
    "detail.period": "기간",
    "detail.target": "대상",
    "detail.description": "소개",
    "detail.requirements": "지원 요건",
    "detail.benefits": "혜택",
    "detail.howToApply": "지원 방법",
    "detail.applyCopy": "필수 자료를 준비하고 자격 요건을 확인한 뒤 마감 전에 공식 링크로 지원하세요.",
    "detail.sourceFallback": "자세한 내용은 원문 공고에서 확인하세요.",
    "detail.record": "지원 상태",
    "detail.related": "관련 기회",
    "detail.qa": "관련 Q&A",
    "detail.openCommunity": "커뮤니티 보기",
    "detail.mentors": "관련 멘토",
    "detail.viewMentors": "멘토 보기",
    "common.emptyTitle": "아직 기회가 없어요.",
    "common.emptyDescription": "다른 카테고리를 선택하거나 필터를 초기화해 보세요.",
    "common.errorTitle": "문제가 발생했어요.",
    "common.errorDescription": "연결 상태를 확인한 뒤 다시 시도해 주세요.",
    "common.retry": "다시 시도",
    "common.loading": "저장 중...",
    "common.loginRequiredTitle": "로그인이 필요해요.",
    "common.loginRequiredDescription": "저장한 기회와 내 정보 기능을 사용하려면 로그인해 주세요.",
    "common.goLogin": "로그인하러 가기",
    "login.title": "Campio 로그인",
    "login.copy": "맞춤 기회 피드로 계속 이동하세요.",
    "login.email": "이메일",
    "login.password": "비밀번호",
    "login.action": "로그인",
    "login.loading": "로그인 중...",
    "login.create": "계정 만들기",
    "login.logout": "로그아웃",
    "signup.title": "Campio 계정 만들기",
    "signup.copy": "프로필을 설정하고 맞춤 기회 추천을 받아보세요.",
    "signup.name": "이름",
    "signup.schoolEmail": "학교 이메일",
    "signup.avatar": "프로필 이미지",
    "signup.avatarHelp": "1MB 이하의 정사각형에 가까운 이미지를 선택해 주세요.",
    "signup.avatarError": "1MB 이하의 이미지 파일을 선택해 주세요.",
    "signup.continue": "계속",
    "signup.loading": "계정 생성 중...",
    "signup.haveAccount": "이미 계정이 있어요",
    "onboarding.title": "Campio 맞춤 설정",
    "onboarding.copy": "학교 정보를 입력하고 피드를 구성할 관심사를 선택하세요.",
    "onboarding.school": "학교",
    "onboarding.major": "전공",
    "onboarding.grade": "학년",
    "saved.kicker": "관심 있는 기회를 관리하세요",
    "saved.title": "저장한 기회.",
    "saved.emptyTitle": "아직 저장한 기회가 없어요.",
    "saved.emptyDescription": "기회를 탐색하고 마음에 드는 항목을 저장해 보세요.",
    "saved.explore": "탐색",
    "community.kicker": "질문, 후기, 팁, 정보를 확인하세요",
    "community.title": "커뮤니티.",
    "community.popular": "인기 질문",
    "community.writeTitle": "제목",
    "community.writeTitlePlaceholder": "공고, 마감일, 면접, 준비 방법에 대해 질문해보세요",
    "community.writeContent": "내용",
    "community.writeContentPlaceholder": "다른 학생들이 답하기 쉽도록 상황을 구체적으로 적어주세요.",
    "community.writeAction": "글 작성",
    "community.emptyTitle": "아직 커뮤니티 글이 없어요.",
    "community.emptyDescription": "궁금한 공고나 지원 과정에 대해 첫 질문을 남겨보세요.",
    "mentors.kicker": "멘토는 더 나은 기회 선택을 도와줍니다",
    "mentors.title": "멘토.",
    "mentors.available": "상담 가능한 멘토",
    "mentors.emptyTitle": "아직 상담 가능한 멘토가 없어요.",
    "mentors.emptyDescription": "검증된 멘토 프로필이 추가되면 공고 선택과 지원 준비를 더 구체적으로 도울 수 있어요.",
    "profile.kicker": "학교 프로필",
    "profile.school": "학교",
    "profile.major": "전공 및 학년",
    "profile.saved": "저장한 기회",
    "profile.interests": "관심사",
    "admin.kicker": "관리자 기회 CRUD 기반",
    "admin.title": "관리자 기회 관리.",
    "admin.create": "기회 생성",
    "admin.colTitle": "제목",
    "admin.colCategory": "카테고리",
    "admin.colOrganization": "기관",
    "admin.colDeadline": "마감일",
    "admin.colStatus": "상태",
    "admin.published": "게시됨",
  },
};

const categoryLabels = {
  ko: {
    All: "전체",
    Internship: "인턴십",
    Competition: "공모전",
    Contest: "공모전",
    "External Activity": "대외활동",
    Scholarship: "장학금",
    Exchange: "교환학생",
    Startup: "창업",
    Seminar: "세미나",
    Mentoring: "멘토링",
    Research: "연구",
    "Government Support": "정부지원",
    Development: "개발",
    Design: "디자인",
    Marketing: "마케팅",
    Finance: "금융",
    AI: "AI",
  },
  en: {},
};

const statusLabels = {
  ko: {
    Saved: "저장됨",
    "Deadline Soon": "마감 임박",
    Applied: "지원 완료",
    Archived: "보관함",
    Interested: "관심 있음",
    Preparing: "준비 중",
    Accepted: "합격",
    Rejected: "불합격",
    INTERESTED: "관심 있음",
    PREPARING: "준비 중",
    APPLIED: "지원 완료",
    ACCEPTED: "합격",
    REJECTED: "불합격",
    ARCHIVED: "보관함",
  },
  en: {
    INTERESTED: "Interested",
    PREPARING: "Preparing",
    APPLIED: "Applied",
    ACCEPTED: "Accepted",
    REJECTED: "Rejected",
    ARCHIVED: "Archived",
  },
};

const locationLabels = {
  ko: {
    Nationwide: "전국",
  },
  en: {
    Nationwide: "Nationwide",
  },
};

const SettingsContext = createContext(null);

function readStoredValue(key, fallback) {
  if (typeof window === "undefined") return fallback;
  return window.localStorage.getItem(key) || fallback;
}

export function SettingsProvider({ children }) {
  const [language, setLanguage] = useState(() => readStoredValue("campio-language", "ko"));
  const [theme, setTheme] = useState(() => readStoredValue(
    "campio-theme",
    typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"
  ));

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    window.localStorage.setItem("campio-theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language === "ko" ? "ko" : "en";
    window.localStorage.setItem("campio-language", language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      theme,
      setTheme,
      t: (key) => copy[language][key] || copy.en[key] || key,
      labelCategory: (valueToLabel) =>
        categoryLabels[language][valueToLabel] || valueToLabel,
      labelLocation: (valueToLabel) =>
        locationLabels[language][valueToLabel] || valueToLabel || "-",
      labelStatus: (valueToLabel) => statusLabels[language][valueToLabel] || valueToLabel,
    }),
    [language, theme]
  );

  return <SettingsContext.Provider value={value}>{children}</SettingsContext.Provider>;
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (!context) {
    throw new Error("useSettings must be used inside SettingsProvider");
  }
  return context;
}
